# Generated by Django 4.0.5 on 2022-07-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
                ('headers', models.ManyToManyField(to='file_exchange.field')),
            ],
        ),
    ]
