# Generated by Django 4.0.5 on 2022-07-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchange', '0003_remove_file_csv_file_csv_dir'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ManyToManyField(to='file_exchange.field')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='listings',
            field=models.ManyToManyField(to='file_exchange.listinginfo'),
        ),
    ]
