# Generated by Django 4.0.5 on 2022-07-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchange', '0004_listinginfo_file_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='listings',
        ),
        migrations.AddField(
            model_name='file',
            name='static',
            field=models.ManyToManyField(related_name='static_fields', to='file_exchange.listinginfo'),
        ),
        migrations.AddField(
            model_name='file',
            name='unique',
            field=models.ManyToManyField(related_name='unique_fields', to='file_exchange.listinginfo'),
        ),
    ]
