# Generated by Django 4.0.5 on 2022-07-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchange', '0005_remove_file_listings_file_static_file_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='unique',
            new_name='listings',
        ),
        migrations.AlterField(
            model_name='file',
            name='static',
            field=models.ManyToManyField(related_name='static_fields', to='file_exchange.field'),
        ),
    ]
