# Generated by Django 4.0.5 on 2022-07-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_exchange', '0006_rename_unique_file_listings_alter_file_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='value',
            field=models.CharField(default='', max_length=31),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(default='', max_length=31),
        ),
    ]
